import {
  BarChart3,
  FileText,
  Layers,
  LayoutDashboard,
  Package,
  Percent,
  Pill,
  Settings,
  ShoppingCart,
  Star,
  Truck,
  Users,
  Warehouse,
} from "lucide-react";

export const menuItems = [
  { icon: LayoutDashboard, label: "Tổng quan", path: "/admin" },
  { icon: Package, label: "Sản phẩm", path: "/admin/product" },
  { icon: Layers, label: "Danh mục", path: "/admin/category" },
  { icon: ShoppingCart, label: "Đơn hàng", path: "/admin/order" },
  { icon: Users, label: "Khách hàng", path: "/admin/user" },
  { icon: Truck, label: "Nhà cung cấp", path: "/admin/supplier" },
  { icon: Warehouse, label: "Kho hàng", path: "/admin/warehouse" },
  { icon: Pill, label: "Đơn thuốc", path: "/admin/prescription" },
  { icon: FileText, label: "Bài viết", path: "/admin/blog" },
  { icon: Percent, label: "Khuyến mãi", path: "/admin/coupone" },
  { icon: Star, label: "Đánh giá", path: "/admin/review" },
  { icon: BarChart3, label: "Báo cáo", path: "/admin/report" },
  { icon: Settings, label: "Cài đặt", path: "/admin/system" },
];
